# Generated by Django 4.0.5 on 2022-11-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
