# Generated by Django 4.1.3 on 2022-11-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
